from enum import Enum


class EnumCustomBotType(Enum):
    MARKET_MAKING_BOT = 1
    PING_PONG_BOT = 2
    SCALPER_BOT = 3
    ORDER_BOT = 4
    FLASH_CRASH_BOT = 6
    INTER_EXCHANGE_ARBITRAGE_BOT = 8
    INTELLIBOT_ALICE_BOT = 9
    ZONE_RECOVERY_BOT = 12
    ACCUMULATION_BOT = 13
    TREND_LINES_BOT = 14
    MAD_HATTER_BOT = 15
    SCRIPT_BOT = 16
    CRYPTO_INDEX_BOT = 17
    HAAS_SCRIPT_BOT = 18
    EMAIL_BOT = 19
    ADVANCED_INDEX_BOT = 20
    BASE_CUSTOM_BOT = 1000
