from enum import Enum

class EnumIndicator(Enum):
    AROON = 0
    AROON_OSCILLATOR = 1
    AWESOME_OSCILLATOR = 2

    BLIND = 3
    BOP = 4
    BBANDS = 5
    BBANDSB = 6
    BBANDSW = 7
    BUY_LOW_SELL_HIGH_FIXED = 8
    BUY_LOW_SELL_HIGH_DYNAMIC = 9
    BBANDS_PSHAI = 51

    CCI = 11
    CMO = 12
    COPPOCK_CURVE = 13
    CRSI = 14
    CANDLE_PATTERN = 15

    DEMA = 16
    DEMA_NEW = 52
    DONCHIAN_CHANNELS = 17
    DPO = 18

    EMA = 19
    EMA_NEW = 53
    ELLIOT = 20

    FASTRSI = 21
    FIBONACCI = 22
    FRACTIAL = 23

    ICHIMOKU_CLOUDS = 24

    JOHNS_CANDELIER = 25

    KELTNER_CHANNELS = 26
    KAMA = 27
    KAMA_NEW = 54
    KELTNERCHANNELS_NEW = 55

    MACD = 28
    MACD_NEW = 69
    MFI = 29
    MOMENTUM = 70

    ROC = 30
    ROCALT = 31
    RSI = 32
    RSI_NEW = 59
    REGRESSION_SLOBE = 33

    SAR = 34
    SLOWRSI = 35
    SMA = 36
    STOCHRSI = 37
    STOCHRSI_NEW = 62
    STOCHASTIC = 38
    STOCHASTIC2 = 39
    SMALL_FRACTIAL = 40
    SCRIPT_INDICATOR = 41

    TEMA = 42
    TEMA_NEW = 63
    TRIX = 43
    TRIX_NEW = 64
    TRIMA = 44
    TRIMA_NEW = 65
    TD = 71
    TELEGRAM_INDICATOR = 45
    TIMED_BLIND = 49

    ULTIMATE_OSCILLATOR = 46
    ULTIMATE_OSCILLATOR_NEW = 66

    WMA = 47
    WILLIAMSW = 48
    WILLIAMSR_NEW = 67

    HAAS_SCRIPT_INDICATOR = 50